import { dump, load } from "js-yaml";
import process from "node:process";
import { readFileSync, writeFileSync } from "fs";

const actionFilePath = "./action.yml";
const versionNumberPattern = /^\d+.\d+.\d+$/;

try {
    const doc = load(readFileSync(actionFilePath, "utf8"));
    const version = getVersionNumber();

    checkKeys(doc);
    doc.inputs["docker-image-version"].default = process.argv[2];
    writeYAMLFile(actionFilePath, doc, version);
} catch (error) {
    console.error("Error loading YAML file:", error);
}

function checkKeys(doc) {
    if (doc.inputs == null) {
        console.error("No 'inputs' key found in yaml file.");
        process.exit(1);
    }

    if (doc.inputs["docker-image-version"] == null) {
        console.error("No 'inputs.docker-image-version' key found in yaml file.");
        process.exit(1);
    }

    if (doc.inputs["docker-image-version"].default == null) {
        console.error("No 'inputs.docker-image-version.default' key found in yaml file.");
        process.exit(1);
    }
}

function getVersionNumber() {
    const args = process.argv;

    if (args.length < 3) {
        console.error(
            `No 'version' argument supplied to this script. Please use the following syntax: 'node tools/docker-image.js <version>'. The <version> arguments has to match the following regex pattern '${versionNumberPattern}'.`
        );
    }

    const version = args[2];

    if (!version.match(versionNumberPattern)) {
        console.error(`The version ${version} does not match the regex pattern '${versionNumberPattern}'.`);
    }
}

function writeYAMLFile(path, doc, version) {
    const yamlDumpOptions = { lineWidth: -1 };

    const yamlDump = dump(doc, yamlDumpOptions);

    const formattedYAMLDump = insertBlankLines(yamlDump);

    writeFileSync(path, formattedYAMLDump, (err) => {
        if (err) {
            console.error(err);
        } else {
            console.log(`Successfully updated ${path} to new version ${version}`);
        }
    });
}

function insertBlankLines(yamlStr) {
    // Generated by ChatGPT
    const lines = yamlStr.split("\n");
    const result = [];

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const nextLine = lines[i + 1];

        result.push(line);
        if (!line.trim()) continue;

        const currentIndent = line.match(/^(\s*)/)[1].length;
        const nextIndent = nextLine ? nextLine.match(/^(\s*)/)[1].length : 0;
        const isTopLevel = currentIndent === 0;
        const isKeyOnly = /:\s*$/.test(line);
        const isNextLessIndented = nextLine && nextIndent < currentIndent;
        const isLastLine = i === lines.length - 1;

        let shouldAddBlankLine = false;

        if (isTopLevel && !isKeyOnly) {
            shouldAddBlankLine = true;
        }

        if (isKeyOnly && nextLine && nextIndent === currentIndent) {
            shouldAddBlankLine = true;
        }

        if (isNextLessIndented) {
            shouldAddBlankLine = true;
        }

        if (shouldAddBlankLine && !isLastLine) {
            const nextNonEmpty = nextLine?.trim();
            if (nextNonEmpty && nextNonEmpty !== "") {
                result.push("");
            }
        }
    }

    return result.join("\n");
}
