name: Release and Docker Build

on:
  push:
    branches:
      - main
      - main-test

permissions:
  contents: read
  packages: write

jobs:
  check-for-release:
    runs-on: ubuntu-24.04

    outputs:
      release: ${{ steps.check_release.outputs.release }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: check-for-releaseing
        id: check_release
        env:
          HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        shell: bash
        run: |
          SAFE_COMMIT_MESSAGE=$(echo "$HEAD_COMMIT_MESSAGE" | head -n1 | sed 's/`/\\`/g')
          if [[ "$SAFE_COMMIT_MESSAGE" =~ ^chore\(release\):\ v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "release=true" >> $GITHUB_OUTPUT
          else
            echo "release=false" >> $GITHUB_OUTPUT
          fi

  build-and-push-docker-image:
    runs-on: ubuntu-24.04

    needs: check-for-release

    env:
      DOCKER_IMAGE: ghcr.io/paulchen5/action-workflow-orchestrator
      VERSION-TAG: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export test image to Docker
        run: |
          make docker-build DOCKER_IMAGE=${{ env.DOCKER_IMAGE }} VERSION=test

      - name: Test test Docker image
        run: |
          docker run --rm ${{ env.DOCKER_IMAGE }}:test
          docker image rm ${{ env.DOCKER_IMAGE }}:test

      - name: Update version
        if: ${{ needs.check-for-release.outputs.release == 'false' }}
        run: |
          VERSION="$(cat VERSION)-sha.${{ github.sha }}"
          echo $VERSION > VERSION
          echo "TAGS=${{ env.DOCKER_IMAGE }}:${VERSION}" >> $GITHUB_ENV

      - name: Update version for release
        if: ${{ needs.check-for-release.outputs.release == 'true' }}
        env:
          HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        shell: bash
        run: |
          SAFE_COMMIT_MESSAGE=$(echo "$HEAD_COMMIT_MESSAGE" | head -n1 | sed 's/`/\\`/g')
          VERSION=$(echo "${SAFE_COMMIT_MESSAGE}" | sed -n "s/^chore(release): v\([0-9]\+\.[0-9]\+\.[0-9]\+\)$/\1/p")
          echo $VERSION > VERSION
          echo "VERSION-TAG=${VERSION}" >> $GITHUB_ENV

      - name: Build production Docker image
        run: |
          make docker-build DOCKER_IMAGE=${{ env.DOCKER_IMAGE }}

      - name: Tag production Docker image
        if: ${{ needs.check-for-release.outputs.release == 'true' }}
        run: |
          docker tag ${{ env.DOCKER_IMAGE }}:${{ env.VERSION-TAG }} ${{ env.DOCKER_IMAGE}}:latest

      - name: Push production Docker image
        run: |
          docker push --all-tags ${{ env.DOCKER_IMAGE }}

  release:
    needs: check-for-release

    if: ${{ needs.check-for-release.outputs.release == 'true' }}

    runs-on: ubuntu-24.04

    env:
      MAJOR_TAG: ""
      RELEASE_NOTES: ""
      TAG: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Project
        uses: ./.github/actions/setup-project/

      - name: Get Release Tag
        env:
          HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        shell: bash
        run: |
          TAG=$(echo "$HEAD_COMMIT_MESSAGE" | sed -n "s/^chore(release): \(v[0-9]\+\.[0-9]\+\.[0-9]\+\)$/\1/p")
          echo "TAG=$TAG" >> $GITHUB_ENV
          if [ -z "${{ env.TAG }}" ]; then
            echo "TAG is empty!"
            exit 1
          fi

      - name: Get Major Tag
        run: |
          MAJOR_TAG=$(echo $TAG | cut -d. -f1)
          echo "MAJOR_TAG=$MAJOR_TAG" >> $GITHUB_ENV
          if [ -z "${{ env.MAJOR_TAG }}" ]; then
            echo "MAJOR_TAG is empty!"
            exit 1
          fi

      - name: Generate Release Notes
        run: |
          RELEASE_NOTES=$(npm run get-last-changelog-entry --silent)
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV

      - name: Create Release with Release assets
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.TAG }}
          tag_name: ${{ env.TAG }}
          body_path: ${{ env.RELEASE_NOTES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Major Version Tag
        run: |
          git tag -f ${{ env.MAJOR_TAG }} ${{ env.TAG }}
          git push origin ${{ env.MAJOR_TAG }} --force
