name: Run Tests

on:
  push:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Project
        uses: ./.github/actions/setup-project/

      - name: Run tests
        run: npm test
